server:
  port: 7779

spring.jpa:
  database: POSTGRESQL
  show-sql: true
spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/cards
  username: mateusz
  password: mateusz123

accounts:
  allow-get-accounts: true

