server:
  port: 7777
spring.jpa:
  database: POSTGRESQL
  show-sql: true

spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/accounts
  username: mateusz
  password: mateusz123
accounts:
 allow-get-accounts: false

